# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build a Java project with Gradle and
# cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call: # allow this workflow to be called by other workflows

concurrency:
  # On master/release, we don't want any jobs cancelled
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/70972844/1261287
  group: ${{ github.ref }}-ci
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    strategy:
      matrix:
        java-version: [11, 17]
      fail-fast: false

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Setup Go environment
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.21.x'

    # at some point this should just be replaced with something that can bring up a sigstore test env
    - name: Install Fulcio
      run: go install github.com/sigstore/fulcio@main

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # tests that hit staging are current disabled due to flakiness (-PskipStaging)
    - name: Test sigstore-java
      run: ./gradlew build -PskipStaging

    - name: Ensure sigstore-java self signing still works
      run: ./gradlew sigstore-java:publishToMavenLocal -Prelease -PskipPgpSigning

    - name: Test sigstore-java/sandbox
      run: |
        cd sandbox
        ./gradlew build
