name: Conformance Tests

on:
  push:
    branches:
      - '**'
  pull_request:
  # TODO: add cron

jobs:
  conformance:
    strategy:
      max-parallel: 1
      matrix:
        java-version: [11, 17]
        sigstore-env: [production, staging]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

      - name: Build sigstore-java cli
        run: ./gradlew :sigstore-cli:build

      - name: Unpack sigstore-java distribution
        run: tar -xvf ${{ github.workspace }}/sigstore-cli/build/distributions/sigstore-cli-*.tar --strip-components 1

      - uses: sigstore/sigstore-conformance@ee4de0e602873beed74cf9e49d5332529fe69bf6 # v0.0.11
        with:
          entrypoint: ${{ github.workspace }}/bin/sigstore-cli
          environment: ${{ matrix.sigstore-env }}
          xfail: "test_verify_dsse_bundle_with_trust_root"
