name: Examples

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-examples
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  examples:
    name: Build and run examples
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Java
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1

    - name: run examples against released sigstore
      working-directory: examples/hello-world
      run: ./test.sh

    - name: install sigstore java development jars into mavenLocal
      run: ./gradlew publishToMavenLocal -Prelease -PskipSigning

    - name: calculate development version
      id: dev_version
      run: |
        set -Exeo pipefail
        echo "version=$(grep "^version=" gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

    - name: run examples against development version
      working-directory: examples/hello-world
      run: ./test.sh -Dsigstore.version=${{ steps.dev_version.outputs.version }}
