name: Release sigstore-java and sigstore-maven-plugin to Maven Central
on:
  workflow_dispatch:
  # user is expected to use a tag as the branch to run the action on

jobs:
  process-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: process tag
        id: version
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#"v"}" >> $GITHUB_OUTPUT
      - name: verify tag matches gradle version
        run: |
          set -Eeo pipefail
          version=$(grep "^version=" gradle.properties | cut -d'=' -f2)
          if [[ ! "$version" == "${{ steps.version.outputs.version }}" ]]; then
            echo "tagged version ${{ github.ref }} (as ${{ steps.version.outputs.version }}) does not match gradle.properties $version"
            exit 1
          fi

  ci:
    needs: [process-tag]
    permissions:
      id-token: write # To run github oidc tests
    uses: ./.github/workflows/ci.yaml

  build:
    permissions:
      id-token: write # To sign the artifacts
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: checkout tag
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up JDK 11
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

      - name: Build, Sign and Release to Maven Central
        run: |
          ./gradlew clean :sigstore-java:publishMavenJavaPublicationToSonatypeRepository :sigstore-maven-plugin:publishMavenJavaPublicationToSonatypeRepository -Prelease
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

  create-release-on-github:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ github.ref_name }}
          body: "See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for more details."
