name: Release sigstore-java and sigstore-maven-plugin to Maven Central
on:
  workflow_dispatch:
  # user is expected to use a tag as the branch to run the action on

jobs:
  process-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: process tag
        id: version
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#"v"}" >> $GITHUB_OUTPUT
      - name: verify tag matches gradle version
        run: |
          set -Eeo pipefail
          version=$(grep "^version=" gradle.properties | cut -d'=' -f2)
          if [[ ! "$version" == "${{ steps.version.outputs.version }}" ]]; then
            echo "tagged version ${{ github.ref }} (as ${{ steps.version.outputs.version }}) does not match gradle.properties $version"
            exit 1
          fi

  ci:
    needs: [process-tag]
    permissions:
      id-token: write # To run github oidc tests
    uses: ./.github/workflows/ci.yaml

  build:
    permissions:
      id-token: write # To sign the artifacts
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: checkout tag
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 11
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v0.8.1
        with:
          workload_identity_provider: projects/306323169285/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: sigstore-java-releaser@sigstore-secrets.iam.gserviceaccount.com

      - uses: google-github-actions/get-secretmanager-secrets@e5bb06c2ca53b244f978d33348d18317a7f263ce # v2.2.2
        id: secrets
        with:
          secrets: |-
            signing_key:sigstore-secrets/sigstore-java-pgp-priv-key
            signing_password:sigstore-secrets/sigstore-java-pgp-priv-key-password
            sonatype_username:sigstore-secrets/sigstore-java-sonatype-username
            sonatype_password:sigstore-secrets/sigstore-java-sonatype-password

      - name: Build, Sign and Release to Maven Central
        run: |
          ./gradlew clean :sigstore-java:publishMavenJavaPublicationToSonatypeRepository :sigstore-maven-plugin:publishMavenJavaPublicationToSonatypeRepository -Prelease
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ steps.secrets.outputs.signing_key }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ steps.secrets.outputs.signing_password }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ steps.secrets.outputs.sonatype_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ steps.secrets.outputs.sonatype_password }}

  create-release-on-github:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          tag_name: ${{ github.ref_name }}
          body: "See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for more details."
