name: Release sigstore gradle plugins to Gradle Plugin Portal
on:
  workflow_dispatch:

jobs:
  process-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: checkout tag
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: process tag
        id: version
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#"v"}" >> $GITHUB_OUTPUT
      - name: verify tag matches gradle version
        run: |
          set -Eeo pipefail
          version=$(grep "^version=" gradle.properties | cut -d'=' -f2)
          if [[ ! "$version" == "${{ steps.version.outputs.version }}" ]]; then
            echo "tagged version ${{ github.ref }} (as ${{ steps.version.outputs.version }}) does not match gradle.properties $version"
            exit 1
          fi

  ci:
    needs: [process-tag]
    permissions:
      id-token: write # To run github oidc tests
    uses: ./.github/workflows/ci.yaml

  build:
    permissions:
      id-token: write # To sign the artifacts
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout tag
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up JDK 11
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1

      - name: Build, Sign and Release to Gradle Plugin Portal
        run: |
          ./gradlew publishPlugins -Prelease -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
