name: TUF Conformance Tests

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
  # TODO: add cron

jobs:
  conformance:
    strategy:
      max-parallel: 1
      matrix:
        java-version: [11, 17]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

      - name: Build tuf cli
        run: ./gradlew :tuf-cli:build

      - name: Unpack tuf distribution
        run: tar -xvf ${{ github.workspace }}/tuf-cli/build/distributions/tuf-cli-*.tar --strip-components 1

      - uses: theupdateframework/tuf-conformance@v2
        with:
          entrypoint: ${{ github.workspace }}/bin/tuf-cli
          artifact-name: test repositories for tuf-cli java ${{ matrix.java-version }}
